--- # this is my HANDLERS file
- hosts: mydemo
  user: ansible
  become: yes
  connection: ssh
  tasks: 
         - name: install httpd
           action: yum name=httpd state=present
           notify: start httpd
  handlers:

           - name: start httpd
             action: service  name=httpd state=restarted    
